apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vmvkfqdew-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vmvkfqdew-java-springboot-gitops